"""FL.ru watcher: RSS parsing, filters, and the alert flow — FL.ru, the model and Telegram are stand-ins."""
import asyncio
import json
from datetime import datetime, timedelta, timezone

import httpx
import pytest

from app import flwatch
from app.config import Settings
from app.consultant import Consultant
from app.flwatch import FlWatch, Project, alert_text, page_description, parse_rss, relevant
from app.notify import Notifier

NOW = datetime(2026, 10, 5, 12, 0, tzinfo=timezone.utc)   # 15:00 in Moscow


def item(pid: str, title: str, category: str, minutes_ago: int, desc: str = "Описание") -> str:
    when = (NOW - timedelta(minutes=minutes_ago)).strftime("%a, %d %b %Y %H:%M:%S GMT")
    return f"""<item>
      <title><![CDATA[{title}]]></title>
      <link>https://www.fl.ru/projects/{pid}/slug.html</link>
      <description><![CDATA[{desc}]]></description>
      <guid>https://www.fl.ru/projects/{pid}/slug.html</guid>
      <category><![CDATA[{category}]]></category>
      <pubDate>{when}</pubDate>
    </item>"""


def feed(*items: str) -> str:   # the shape FL.ru serves, comment and CDATA included
    return ('<?xml version="1.0" encoding="utf-8"?><!--  RSS generated by FL.ru RSS Generator -->\n'
            '<rss version="2.0"><channel><title>Заказы на FL.ru</title>' + "".join(items) + "</channel></rss>")


PAGE = """<div id="project_info_5524460" class="b-layout"><div class="b-layout">
<div id="projectp5524460" class="text-5 pb-20 fl-project-content__description-text ">
   Есть уже сделанный парсер в TG + интегрированный ИИ <br /> <br />Бот присылает дубликаты &quot;4 раза&quot;  </div>
<div><div class="text-10 opacity-50">Опубликован 05.10.2026 в 14:41</div></div></div></div>"""

BOT = item("5524460", "Доработка существующего бота-парсера Telegram (Бюджет: 9 000  &#8381;)",
           "Программирование / Разработка Чат-ботов", 5, "Есть уже сделанный парсер в TG...")
VIDEO = item("5524493", "Создать видео", "AI — искусственный интеллект / Генерация видео", 3)
CHEAP = item("5524035", "Сделать ии бота (Бюджет: 500  &#8381;, для всех)", "AI — искусственный интеллект / Боты с AI", 4)
OLD = item("5520343", "Создать бота в мессенджере Макс/тг", "Мессенджеры / MAX", 60 * 30)
APPSTORE = item("5524153", "Опубликовать игру в AppStore на своем аккаунте (для всех)", "Программирование / iOS", 7)


def test_parse_rss_reads_budget_audience_and_dates():
    projects = {p.id: p for p in parse_rss(feed(BOT, CHEAP, APPSTORE))}
    bot = projects["5524460"]
    assert bot.title == "Доработка существующего бота-парсера Telegram" and bot.budget == "9 000 ₽"
    assert bot.budget_rub == 9000 and not bot.for_all
    assert bot.category == "Программирование / Разработка Чат-ботов"
    assert bot.published == NOW - timedelta(minutes=5)
    assert projects["5524035"].budget_rub == 500 and projects["5524035"].for_all
    store = projects["5524153"]
    assert store.title == "Опубликовать игру в AppStore на своем аккаунте" and store.for_all and store.budget == ""


def test_full_description_comes_from_the_project_page():
    assert page_description(PAGE) == 'Есть уже сделанный парсер в TG + интегрированный ИИ\n\nБот присылает дубликаты "4 раза"'
    assert page_description("<html>nothing</html>") == ""


def test_relevance_filters():
    ps = {p.id: p for p in parse_rss(feed(BOT, VIDEO, APPSTORE))}
    assert relevant(ps["5524460"]) and relevant(ps["5524153"])
    assert not relevant(ps["5524493"])                    # AI video generation is not his work
    office = Project("1", "Python-разработчик для чат-бота, работа в офисе", "u", "Программирование / Python", NOW)
    assert not relevant(office)


# ---------- the whole flow ----------
def settings(tmp_path, **kw) -> Settings:
    return Settings(llm_url="https://llm.test/v1/chat/completions", llm_auth="Api-Key k", llm_model="m",
                    telegram_token="123:ABC", telegram_api="https://tg.test", db_path=tmp_path / "db.sqlite",
                    fl_watch=True, fl_categories="5,31", **kw)


class Fake:
    """FL.ru (feeds + project pages), the model and Telegram in one MockTransport."""

    def __init__(self, fit=8, fl_down=False, tg_down=False):
        self.feed = feed(BOT)
        self.fit, self.fl_down, self.tg_down = fit, fl_down, tg_down
        self.llm_calls, self.sent = [], []

    def handler(self, request: httpx.Request) -> httpx.Response:
        host = request.url.host
        if host == "www.fl.ru":
            if self.fl_down:
                return httpx.Response(503)
            if request.url.path == "/rss/all.xml":
                return httpx.Response(200, content=self.feed.encode())
            return httpx.Response(200, text=PAGE)
        if host == "llm.test":
            self.llm_calls.append(json.loads(request.content))
            answer = {"fit": self.fit, "why": "مطابق لخبرتك في البوتات", "price": "9 000 ₽", "days": "5 дней",
                      "reply": "Здравствуйте! Возьмусь за **все** три задачи."}
            return httpx.Response(200, json={"choices": [{"message": {"content": "```json\n" + json.dumps(
                answer, ensure_ascii=False) + "\n```"}}]})
        if host == "tg.test":
            self.sent.append(json.loads(request.content))
            if self.tg_down == "refused":   # the relay answers 200 with Telegram's refusal inside
                return httpx.Response(200, json={"ok": False, "description": "Bad Request: can't parse entities"})
            return httpx.Response(502 if self.tg_down else 200, json={"ok": not self.tg_down})
        raise AssertionError(f"unexpected request {request.url}")

    def client(self):
        return httpx.AsyncClient(transport=httpx.MockTransport(self.handler))


def watcher(tmp_path, fake: Fake, **kw) -> FlWatch:
    s = settings(tmp_path, **kw)
    client = fake.client()
    return FlWatch(s, Notifier(s.telegram_token, s.telegram_api, client), "-100500",
                   llm=Consultant(s, client), client=client, db=tmp_path / "fl.sqlite")


def test_first_start_marks_feed_as_old_then_alerts_new_fitting_project(tmp_path):
    async def body():
        fake = Fake()
        fake.feed = feed(OLD)
        w = watcher(tmp_path, fake)
        assert await w.tick(NOW) == []
        assert len(fake.sent) == 1 and "اشتغل" in fake.sent[0]["text"] and not fake.llm_calls

        w.seen.meta("sample", "skip")              # the one-off example alert has its own test
        fake.feed = feed(OLD, BOT, VIDEO, CHEAP)
        sent = await w.tick(NOW)
        assert [p.id for p in sent] == ["5524460"]          # video: not his work; 500 ₽: too cheap
        assert len(fake.llm_calls) == 1
        task = fake.llm_calls[0]["messages"][1]["content"]
        assert "Бот присылает дубликаты" in task            # the full description from the project page
        msg = fake.sent[-1]
        assert msg["text"].startswith("🟢 <b>FL.ru · 8/10</b>") and "<pre>Здравствуйте! Возьмусь за все три задачи.</pre>" in msg["text"]
        assert "السعر <b>9000</b>" in msg["text"] and "المدة <b>5</b>" in msg["text"]
        assert msg["reply_markup"]["inline_keyboard"][0][0]["url"] == "https://www.fl.ru/projects/5524460/slug.html"
        assert "disable_notification" not in msg            # 15:00 in Moscow: with sound

        assert await w.tick(NOW) == [] and len(fake.llm_calls) == 1   # never twice
    asyncio.run(body())


def test_low_fit_is_not_sent(tmp_path):
    async def body():
        fake = Fake(fit=4)
        fake.feed = feed(OLD)
        w = watcher(tmp_path, fake)
        await w.tick(NOW)
        w.seen.meta("sample", "skip")
        fake.feed = feed(OLD, BOT)
        assert await w.tick(NOW) == [] and len(fake.sent) == 1 and len(fake.llm_calls) == 1
    asyncio.run(body())


def test_telegram_failure_retries_without_asking_the_model_again(tmp_path):
    async def body():
        fake = Fake()
        fake.feed = feed(OLD)
        w = watcher(tmp_path, fake)
        await w.tick(NOW)
        w.seen.meta("sample", "skip")
        fake.feed, fake.tg_down = feed(OLD, BOT), True
        assert await w.tick(NOW) == []
        fake.tg_down = False
        assert [p.id for p in await w.tick(NOW)] == ["5524460"] and len(fake.llm_calls) == 1
    asyncio.run(body())


def test_telegram_refusal_behind_the_relay_is_a_failure(tmp_path):
    async def body():
        fake = Fake()
        fake.feed = feed(OLD)
        w = watcher(tmp_path, fake)
        await w.tick(NOW)
        w.seen.meta("sample", "skip")
        fake.feed, fake.tg_down = feed(OLD, BOT), "refused"
        assert await w.tick(NOW) == [] and "5524460" not in w.seen.known()
        assert flwatch.STATUS["last_error"] == "telegram: RuntimeError"
    asyncio.run(body())


def test_daily_limit(tmp_path):
    async def body():
        fake = Fake()
        fake.feed = feed(OLD)
        w = watcher(tmp_path, fake, fl_daily_max=1)
        await w.tick(NOW)
        w.seen.meta("sample", "skip")
        fake.feed = feed(OLD, BOT, APPSTORE)
        assert len(await w.tick(NOW)) == 1
    asyncio.run(body())


def test_warns_once_when_fl_is_down_and_says_when_it_is_back(tmp_path):
    async def body():
        fake = Fake()
        fake.feed = feed(OLD)
        w = watcher(tmp_path, fake)
        await w.tick(NOW)
        fake.fl_down = True
        for _ in range(7):
            await w.tick(NOW)
        warnings = [m for m in fake.sent if m["text"].startswith("⚠️")]
        assert len(warnings) == 1 and flwatch.STATUS["failures"] == 7
        fake.fl_down = False
        await w.tick(NOW)
        assert fake.sent[-1]["text"].startswith("✅ FL.ru رجع") and flwatch.STATUS["failures"] == 0
    asyncio.run(body())


def test_night_alerts_are_silent(tmp_path):
    async def body():
        fake = Fake()
        fake.feed = feed(OLD)
        w = watcher(tmp_path, fake)
        night = datetime(2026, 10, 5, 23, 10, tzinfo=timezone.utc)    # 02:10 in Moscow
        await w.tick(night)
        w.seen.meta("sample", "skip")
        fake.feed = feed(OLD, item("5524999", "Telegram-бот с ИИ для записи клиентов", "AI — искусственный интеллект / Боты с AI", 0))
        fake.feed = fake.feed.replace((NOW).strftime("%a, %d %b %Y %H:%M:%S GMT"), night.strftime("%a, %d %b %Y %H:%M:%S GMT"))
        await w.tick(night)
        assert fake.sent[-1]["disable_notification"] is True
    asyncio.run(body())


def test_one_example_alert_after_start(tmp_path):
    async def body():
        fake = Fake()
        fake.feed = feed(OLD)
        w = watcher(tmp_path, fake)
        await w.tick(NOW)                              # first start: hello
        fake.feed = feed(OLD, BOT)                     # BOT is now in the feed but counted as old below
        w.seen.add(parse_rss(feed(BOT))[0], -1, False)
        assert await w.tick(NOW) == []
        example = fake.sent[-1]
        assert example["text"].startswith("🧪") and "Доработка существующего бота-парсера" in example["text"]
        assert flwatch.STATUS["sample"] == "sent: 5524460 fit 8"
        n = len(fake.sent)
        await w.tick(NOW)
        assert len(fake.sent) == n                     # only once
    asyncio.run(body())


def test_model_output_quirks():
    v = flwatch.parse_verdict('Вот ответ: {"fit": "7", "why": "x", "price": "от 25 000 ₽", "days": "5–7 дней", '
                              '"reply": "Здравствуйте!\nСтрока два"}')
    assert (v.fit, v.price, v.days) == (7, "25000", "5") and v.reply == "Здравствуйте!\nСтрока два"
    with pytest.raises(ValueError):
        flwatch.parse_verdict('{"fit": 9, "reply": ""}')


def test_alert_without_model_still_useful():
    p = Project("1", "Бот <для> записи", "https://www.fl.ru/projects/1/x.html", "AI / Боты с AI",
                NOW - timedelta(minutes=90), summary="Нужен бот")
    text = alert_text(p, None, NOW)
    assert text.startswith("🟡 <b>FL.ru</b>") and "&lt;для&gt;" in text and "من 1 ساعة" in text
